log discovery requests
tinkerbell/boots pull request #173
Opened 2021-07-01 19:22 UTC by mikemrm

Discovery requests call an external service, by logging this, it's
easier to track a request when it takes this path.

2021-07-01 19:26 UTC, mmlb requested changes

2021-07-01 19:26 UTC, mmlb commented on cmd/boots/main.go
> +	client.Logger = l
would prefer to have NewClient gain a log.Logger param

2021-07-01 20:59 UTC, mmlb requested changes

2021-07-01 20:59 UTC, mmlb commented on packet/client.go
> +	Logger         log.Logger
make private

2021-07-01 20:59 UTC, mmlb commented on packet/client.go
> +func NewClient(consumerToken, authToken string, baseURL *url.URL, logger log.Logger) (*Client, error) {
lets do it as first param.

2021-07-01 21:44 UTC, mikemrm commented on packet/client.go
> +func NewClient(consumerToken, authToken string, baseURL *url.URL, logger log.Logger) (*Client, error) {
gah, you're right!

2021-07-27 16:55 UTC, tstromberg approved these changes

2021-08-24 15:47 UTC, mmlb submitted a review, later dismissed
just needs a rebase @mikemrm

2021-08-24 15:51 UTC, mmlb commented
> just needs a rebase @mikemrm

nm I was able to do the rebase and push

2021-09-21 15:26 UTC, jacobweinstock commented
Hey @mikemrm, looks like there's just a single file merge conflict but other than that should be could to go.

2021-09-21 16:04 UTC, merged